<!DOCTYPE html>
<html lang="pt-br">
<head>
	<!--Página desenvolvida por: Diego Fernandes--> 
	<meta charset="UTF-8">	
	<title>Titina Micro Framework</title>

	<link rel="stylesheet" type="text/css" href="/assets/css/style.css">
	<link rel="icon" href="/logo.png" type="image/x-icon">
</head>
<body>

	<input type="checkbox" id="bt_menu">
	<label for="bt_menu">&#9776;</label>

	<nav class="menu">
		<ul>
			<li id="Titina"><img src="/logo.png" class="logoMenu" alt="logotipo Titina Framework">Titina Framework</li>
			<li><a href="/">Home</a></li>
		</ul>			
	</nav>

	<div class="p404">
		
	<h1>Opa, calma aí fera!</h1><br><br>
	<p>Verifique a URL digitada e tente novamente. <br> Ou volte para o início clicando em Home. </p>

	</div>

</body>

</html>






