<div class="row">
	<h1 id="home">Home</h1>
</div>

<div class="presentation">
	<h2>Titina Micro Framework</h2><br><br><br>
	<div class="resume"><p>Este é um Micro Framework MVC em PHP, construído como exercício do conteúdo didático do curso "Micro Framework do Zero" disponibilizado no canal TJG Web no Youtube.</p><br>
		<p>Este curso foi proposto pela Infojr-UFBA como exercício final do processo Trainee 2017.2.</p></div>
</div>

<!--<p>Nome: <?php //echo $this->view->nome ?></p>-->