<!DOCTYPE html>
<html lang="pt-br">
<head>
	<!--Página desenvolvida por: Diego Fernandes--> 
	<meta charset="UTF-8">	
	<title><?php $this->getPageTitle('|') ?>Titina Micro Framework</title>

	<link rel="stylesheet" type="text/css" href="/assets/css/style.css">
</head>
<body>

	<input type="checkbox" id="bt_menu">
	<label for="bt_menu">&#9776;</label>

	<nav class="menu">
	<ul>
		<li><a href="/">Titina Framework</a></li>
		<li><a href="/">Home</a></li>
		<li><a href="/posts">Posts</a></li>
	</ul>			
</nav>

	<?php $this->content() ?>
	
</body>
</html>






